//
//  AccountDetailPresenter.swift
//  BankTest
//
//  Created by Jaber Vieira Da Silva Shamali on 05/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountDetailPresentationLogic{
  func presentSomething(response: AccountDetail.Something.Response)
}

class AccountDetailPresenter: AccountDetailPresentationLogic{
  weak var viewController: AccountDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AccountDetail.Something.Response){
    let viewModel = AccountDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
