//
//  AccountDetailInteractor.swift
//  BankTest
//
//  Created by Jaber Vieira Da Silva Shamali on 05/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountDetailBusinessLogic{
  func doSomething(request: AccountDetail.Something.Request)
}

protocol AccountDetailDataStore{
  var clienteData: Cliente { get set }
}

class AccountDetailInteractor: AccountDetailBusinessLogic, AccountDetailDataStore{
    var presenter: AccountDetailPresentationLogic?
    var worker: AccountDetailWorker?
    var clienteData = Cliente()

  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AccountDetail.Something.Request){
    worker = AccountDetailWorker()
    worker?.doSomeWork()
    
    let response = AccountDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
